[project]
name = "appzip"
version = "0.1.0"
description = "Bundle your python application as a cross-platform executable zip app."
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
appzip = "appzip:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13"]
build-backend = "uv_build"